In [1]:
import numpy as np
import pandas as pd

In [40]:
df = pd.DataFrame(np.random.rand(5,1))

In [8]:
df

0         1         2         3         4         5         6  \
0  0.408960  0.070678  0.373957  0.184759  0.387744  0.297897  0.419459   
1  0.727940  0.296188  0.474564  0.686255  0.417673  0.813233  0.470842   
2  0.415176  0.157863  0.505621  0.221435  0.855086  0.025044  0.969605   
3  0.090440  0.115193  0.011438  0.590517  0.311081  0.065849  0.782758   
4  0.349774  0.583724  0.885829  0.780260  0.608362  0.182307  0.801069   

          7         8         9  
0  0.575106  0.739666  0.549785  
1  0.465917  0.633147  0.564085  
2  0.054979  0.176395  0.346994  
3  0.952024  0.174356  0.811625  
4  0.613466  0.991041  0.803071

In [24]:
df.rename({'0':'A','1':'B','3':'C'},inplace=True)
df

0         1         2         3         4         5         6  \
0  0.408960  0.070678  0.373957  0.184759  0.387744  0.297897  0.419459   
1  0.727940  0.296188  0.474564  0.686255  0.417673  0.813233  0.470842   
2  0.415176  0.157863  0.505621  0.221435  0.855086  0.025044  0.969605   
3  0.090440  0.115193  0.011438  0.590517  0.311081  0.065849  0.782758   
4  0.349774  0.583724  0.885829  0.780260  0.608362  0.182307  0.801069   

          7         8         9  
0  0.575106  0.739666  0.549785  
1  0.465917  0.633147  0.564085  
2  0.054979  0.176395  0.346994  
3  0.952024  0.174356  0.811625  
4  0.613466  0.991041  0.803071

In [30]:
df.reset_index(drop=True)

0         1         2         3         4         5         6  \
0  0.408960  0.070678  0.373957  0.184759  0.387744  0.297897  0.419459   
1  0.727940  0.296188  0.474564  0.686255  0.417673  0.813233  0.470842   
2  0.415176  0.157863  0.505621  0.221435  0.855086  0.025044  0.969605   
3  0.090440  0.115193  0.011438  0.590517  0.311081  0.065849  0.782758   
4  0.349774  0.583724  0.885829  0.780260  0.608362  0.182307  0.801069   

          7         8         9  
0  0.575106  0.739666  0.549785  
1  0.465917  0.633147  0.564085  
2  0.054979  0.176395  0.346994  
3  0.952024  0.174356  0.811625  
4  0.613466  0.991041  0.803071

In [37]:
index = ['a','b','c','d','e']
df

0         1         2         3         4         5         6  \
0  0.408960  0.070678  0.373957  0.184759  0.387744  0.297897  0.419459   
1  0.727940  0.296188  0.474564  0.686255  0.417673  0.813233  0.470842   
2  0.415176  0.157863  0.505621  0.221435  0.855086  0.025044  0.969605   
3  0.090440  0.115193  0.011438  0.590517  0.311081  0.065849  0.782758   
4  0.349774  0.583724  0.885829  0.780260  0.608362  0.182307  0.801069   

          7         8         9  
0  0.575106  0.739666  0.549785  
1  0.465917  0.633147  0.564085  
2  0.054979  0.176395  0.346994  
3  0.952024  0.174356  0.811625  
4  0.613466  0.991041  0.803071

In [60]:
# 1 iterate over row
input_df = [{'name':'Sujeet', 'age':10},
            {'name':'Sameer', 'age':11},
            {'name':'Sumit', 'age':12}]
cdf= pd.DataFrame(input_df)
print(cdf)

print("iterate over rows \n")
for index,row in cdf.iterrows():
    print(row['name'],row['age'])

     name  age
0  Sujeet   10
1  Sameer   11
2   Sumit   12
iterate over rows 

Sujeet 10
Sameer 11
Sumit 12


In [62]:
df

name  age
0  Sujeet   10
1  Sameer   11
2   Sumit   12

In [68]:
# 2. using some condition
ndf = df[(df['age']>10)]
ndf

name  age
1  Sameer   11
2   Sumit   12

In [73]:
# 3. show only specific row
df.loc[[1],:]


name  age
1  Sameer   11

In [72]:
# 4. show onlys specific columns
df.loc[:,["age"]]

age
0   10
1   11
2   12

In [84]:
# limited row selection
df.loc[:]

name  age
0  Sujeet   10
1  Sameer   11
2   Sumit   12

In [21]:
# number of rows and columns of matrix
import numpy as np
mm = np.array([[ 1, 10,  3],[ 4,  5,  6]])
mm

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [47]:
#select the given element in the above matrix
mm[0][2]

3

In [68]:
#sum of digonal elements
mm.sum(axis=0)

array([ 5, 15,  9])

In [70]:
#addition and substraction using numpy
for i in mm:
   np.sum()

TypeError: _sum_dispatcher() missing 1 required positional argument: 'a'

In [73]:
# reverse numpy array
nn = np.array([1,2,3,4,5])
nn

array([1, 2, 3, 4, 5])

In [77]:
#reverse a array
ns=nn[::-1]
ns

array([5, 4, 3, 2, 1])

In [78]:
ns.multiplication()

AttributeError: 'numpy.ndarray' object has no attribute 'multiplication'